version: 2
jobs:
  build:
    docker:      
      - image: circleci/node:10
      - image: circleci/postgres:9.6-alpine-postgis-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: bookify_test
    
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-yarn-cache-{{ checksum "yarn.lock" }}
            - v1-yarn-cache-

      - run: yarn install --frozen-lockfile
      
      - save_cache:
          key: v1-yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

      # run tests!
      - run: yarn features
